#!/bin/bash
#check if folder does not exist and create it
# User to be generated by backend
USER=$(whoami)
echo $USER
RIDEID=Ride010
echo "user serial generated $(USER)"
mkdir -p $USER/$RIDEID
echo "user folder generated"
echo $USER $RIDEID

#change directory to created folder
cd $USER/$RIDEID

​
#source ros melodic to enable usage of ros command
# source /opt/ros/melodic/setup.bash
# echo "Ros2 was sourced successfully"
​# record bag to all available topics
echo "start rosbag recording to all active topics"



#start recording
#   echo "new bag"
  #ros2 bag record -a --split --duration=5m #ros2 foxy works with this
  
# rosbag record --split 2m --duration 20m -a #recording rosbag into 100mb chunks
rosbag record --duration 1m --split -a


